---
- name: Debug info
  hosts: zookeeper
  tasks:
    - name: hostvars
      debug: var=hostvars
    - name: groups
      debug: var=groups
    - name: ansible_facts
      debug: var=ansible_facts
    - set_fact:
        zid: "{{ groups['zookeeper'].index(inventory_hostname) }}"

    - name: Echo
      shell: "echo {{ zid }}"
      register: echo
    - debug: var=echo.stdout_lines

    - debug:
        msg: "{{ zid }}"
        x: 1

