---
- name: Debug info
  hosts: 129.*
  tasks:
    - name: hostvars
      debug: var=hostvars
    - name: groups
      debug: var=groups
    - name: ansible_facts
      debug: var=ansible_facts

#    - name: hostname
#      shell: hostname
#      register: hostname
#    - debug: var=hostname.stdout_lines

#    - name: Echo
#      shell: "echo {{ zookeeper_servers }} {{ service_url }} {{ http_url }} "
#      register: echo
#    - debug: var=echo.stdout_lines

