- name: Pulsar setup
  hosts: zookeeper, bookie, broker, proxy, client
  tasks:
    - name: Create necessary directories
      file:
        path: "/opt/pulsar"
        state: directory
    - name: Install helper packages
      dnf:
        name: [sysstat, vim]
    - name: Set sysctl params
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict:
        fs.file-max: 1572864000
        fs.nr_open: 157286400
        vm.max_map_count: 1966080
    - name: Set pulsar_version fact
      set_fact:
        pulsar_version: "2.6.0"
    - name: check if pulsar has already been unpacked
      stat:
        path: /opt/pulsar/bin/pulsar
      register: result
    - name: Download the Pulsar binary package
      get_url:
        url: https://archive.apache.org/dist/pulsar/pulsar-{{ pulsar_version }}/apache-pulsar-{{ pulsar_version }}-bin.tar.gz
        dest: /opt/apache-pulsar-{{ pulsar_version }}-bin.tar.gz
        checksum: sha256:5b5f93e4460576b48a2f685311428bab777fead2e1d83a987f79a100f6b6e924
      when: result.stat.exists == false
    - name: Unpack the Pulsar binary package
      unarchive:
        src: /opt/apache-pulsar-{{ pulsar_version }}-bin.tar.gz
        remote_src: yes
        dest: /opt/pulsar
        extra_opts: ["--strip-components=1"]
      when: result.stat.exists == false
    - name: Set URL facts
      set_fact:
        zookeeper_servers: "{{ groups['zookeeper'] }}"
        service_url: "pulsar://{{ groups['proxy'][0] }}:6650/"
        http_url: "http://{{ groups['proxy'][0] }}:8080/"
    - name: Echo
      shell: "echo {{ zookeeper_servers }} {{ service_url }} {{ http_url }} "
      register: echo
    - debug: var=echo.stdout_lines
